-- Re-Charge — instant phone/browser alerts (Web Push) for new leads, accepted
-- quotes and payments.
--
--   push_subscriptions  one row per device that turned alerts on in the panel
--                       (Settings → Phone alerts). Staff only.
--   push_keys           the VAPID key pair that signs the alerts. Generated by the
--                       notify-push function on first use; RLS on with no
--                       policies, so only the service role can read it.

create table if not exists push_subscriptions (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid references auth.users(id) on delete cascade,
  endpoint    text not null unique,
  p256dh      text not null,
  auth        text not null,
  label       text,
  created_at  timestamptz not null default now(),
  last_ok_at  timestamptz,
  last_error  text
);
alter table push_subscriptions enable row level security;
drop policy if exists push_subscriptions_staff on push_subscriptions;
create policy push_subscriptions_staff on push_subscriptions for all using (is_staff()) with check (is_staff());

create table if not exists push_keys (
  id          integer primary key default 1 check (id = 1),
  public_key  text not null,
  private_key text not null,
  created_at  timestamptz not null default now()
);
alter table push_keys enable row level security;
